name: Build and push images to Registry

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
  workflow_dispatch:

env:
  REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}

jobs:
  # Build Controller (Go backend)
  build-controller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      
      - name: Normalize registry host
        run: |
          REGISTRY="${REGISTRY_HOST}"
          REGISTRY="${REGISTRY#http://}"
          REGISTRY="${REGISTRY#https://}"
          REGISTRY="${REGISTRY%/}"
          echo "REGISTRY=$REGISTRY" >> "$GITHUB_ENV"
      
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/nirantar-controller
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
          labels: |
            org.opencontainers.image.title=Nirantar Controller
            org.opencontainers.image.description=Go backend API for Nirantar RTMP streaming system
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.vendor=Shital AI
            org.opencontainers.image.authors=Shital AI
      
      - uses: docker/build-push-action@v5
        with:
          context: ./apps/controller
          file: ./apps/controller/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Build Web Admin (Next.js frontend)
  build-web-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      
      - name: Normalize registry host
        run: |
          REGISTRY="${REGISTRY_HOST}"
          REGISTRY="${REGISTRY#http://}"
          REGISTRY="${REGISTRY#https://}"
          REGISTRY="${REGISTRY%/}"
          echo "REGISTRY=$REGISTRY" >> "$GITHUB_ENV"
      
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/nirantar-web-admin
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
          labels: |
            org.opencontainers.image.title=Nirantar Web Admin
            org.opencontainers.image.description=Next.js dashboard for Nirantar RTMP streaming system
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.vendor=Shital AI
            org.opencontainers.image.authors=Shital AI
      
      - uses: docker/build-push-action@v5
        with:
          context: ./apps/web-admin
          file: ./apps/web-admin/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Build Relay (RTMP relay service)
  build-relay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      
      - name: Normalize registry host
        run: |
          REGISTRY="${REGISTRY_HOST}"
          REGISTRY="${REGISTRY#http://}"
          REGISTRY="${REGISTRY#https://}"
          REGISTRY="${REGISTRY%/}"
          echo "REGISTRY=$REGISTRY" >> "$GITHUB_ENV"
      
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/nirantar-relay
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
          labels: |
            org.opencontainers.image.title=Nirantar Relay
            org.opencontainers.image.description=RTMP relay service for multi-destination streaming
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.vendor=Shital AI
            org.opencontainers.image.authors=Shital AI
      
      - uses: docker/build-push-action@v5
        with:
          context: ./apps/relay
          file: ./apps/relay/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Build Loop Publisher (Backup stream publisher)
  build-loop-publisher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      
      - name: Normalize registry host
        run: |
          REGISTRY="${REGISTRY_HOST}"
          REGISTRY="${REGISTRY#http://}"
          REGISTRY="${REGISTRY#https://}"
          REGISTRY="${REGISTRY%/}"
          echo "REGISTRY=$REGISTRY" >> "$GITHUB_ENV"
      
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/nirantar-loop-publisher
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
          labels: |
            org.opencontainers.image.title=Nirantar Loop Publisher
            org.opencontainers.image.description=Backup loop video publisher for failover streaming
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.vendor=Shital AI
            org.opencontainers.image.authors=Shital AI
      
      - uses: docker/build-push-action@v5
        with:
          context: ./apps/loop-publisher
          file: ./apps/loop-publisher/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
